language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - gnupg
      - zip
install:
  - pip install -r requirements.txt
  - pip install pylint
script:
  - make build
  - make test
  - make lint
